export const commonTools = [
  "Clio",
  "PracticePanther",
  "Cosmolex",
  "LexisNexis",
  "Westlaw",
  "DocuSign",
  "Everlaw",
  "Relativity",
  "CaseText",
  "Epic",
  "Cerner",
  "eClinicalWorks",
  "Allscripts",
  "Meditech",
  "Athenahealth",
  "DrChrono",
  "Kareo",
  "AdvancedMD",
  "PubMed",
  "HouseCanary",
  "Zillow Premier Agent",
  "Redfin",
  "Realtor.com",
  "Matterport",
  "BoomTown",
  "kvCORE",
  "ShowingTime",
  "QuickBooks",
  "Xero",
  "FreshBooks",
  "Sage Intacct",
  "NetSuite",
  "BlackLine",
  "Wave",
  "BambooHR",
  "ADP",
  "Workday",
  "Gusto",
  "Zenefits",
  "Paylocity",
  "TriNet",
  "Namely",
  "SAP SuccessFactors",
  "UKG Pro",
  "Wonderware",
  "Rockwell Automation",
  "Siemens TIA Portal",
  "ABB Ability",
  "SCADA",
  "MES",
  "PLC",
  "Guidewire",
  "Duck Creek",
  "Applied Epic",
  "Vertafore",
  "Insurity",
  "Salesforce Financial Services Cloud",
  "MercuryGate",
  "JDA",
  "Oracle Transportation Management",
  "SAP Transportation Management",
  "BluJay",
  "Descartes",
  "Manhattan Associates",
  "FourKites",
  "Project44",
  "SAP ERP",
  "Oracle NetSuite",
  "Siemens Teamcenter",
  "DELMIAWorks",
  "Fishbowl",
  "MRPeasy",
  "Toast POS",
  "Square POS",
  "TouchBistro",
  "Upserve",
  "Revel Systems",
  "OpenTable",
  "7shifts",
  "Restaurant365",
  "Grubhub",
  "DoorDash",
  "Uber Eats",
  "Shopify",
  "WooCommerce",
  "Magento",
  "BigCommerce",
  "Salesforce Commerce Cloud",
  "PayPal",
  "Stripe",
  "Google Analytics",
  "Looker",
  "Klaviyo",
  "Omnisend",
  "ShipStation",
  "Lightspeed",
  "Amadeus",
  "Sabre",
  "Galileo",
  "Worldspan",
  "Booking.com",
  "Expedia",
  "Agoda",
  "Hotelbeds",
  "Skyscanner",
  "Kiwi.com",
  "Google Flights",
  "Concur Travel",
  "TripActions",
  "Travelport",
  "Travefy",
  "TripIt",
  "Slack",
  "Microsoft Teams",
  "Zoom",
  "Google Workspace",
  "Dropbox",
  "Box",
  "Trello",
  "Asana",
  "Jira",
  "Monday.com",
  "Notion",
  "GitHub",
  "GitLab",
  "Bitbucket",
  "Zapier",
  "MuleSoft",
  "Workato",
  "Boomi",
  "Tableau",
  "Power BI",
  "Domo",
  "Segment",
  "Mixpanel",
  "Intercom",
  "Zendesk",
  "HubSpot",
  "Salesforce",
  "Pipedrive",
  "Marketo",
  "Mailchimp",
  "Constant Contact",
  "SurveyMonkey",
  "Typeform",
  "Calendly",
  "DocSend",
  "PandaDoc",
  "HelloSign",
  "Adobe Sign",
];
